### ISSUE TITLE
Change code length in bank information service

### ISSUE THREAD

**Issue by atoyansk** [tomaszwpasternak/ng2-iban#21]
I'm trying to use validation and bank information service to Israel. But I noticed that the "code" item must be a 4-numbers length string.
The problem is that in Israel the code of bank branches are 3-numbers length.

`[
    {
      "locale": "IL",
      "codes": [
        {
          "code": "012",
          "information": {
            "img": "https://...",
            "title": "בנק הפועלים"
          }
        }
      ]
    }
  ]`

How can I change this parameter in order to the service can accept the right code?

**Comment by tomaszwpasternak** [comment]
Hello, 

I wasn't aware that fact. I'll fix it immediately.
